name: keras2-tf27
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _ipython_minor_entry_point=8.7.0=h8cf3c4a_0
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - abseil-cpp=20210324.2=h9c3ff4c_0
  - absl-py=1.3.0=pyhd8ed1ab_0
  - aiohttp=3.8.3=py39hb9d737c_1
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - asttokens=2.2.1=pyhd8ed1ab_0
  - astunparse=1.6.3=pyhd8ed1ab_0
  - async-timeout=4.0.2=pyhd8ed1ab_0
  - attrs=22.1.0=pyh71513ae_1
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=pyhd8ed1ab_3
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - bedtools=2.30.0=h468198e_3
  - biopython=1.80=py39hb9d737c_0
  - blinker=1.5=pyhd8ed1ab_0
  - brotlipy=0.7.0=py39hb9d737c_1005
  - bzip2=1.0.8=h7f98852_4
  - c-ares=1.18.1=h7f98852_0
  - ca-certificates=2022.12.7=ha878542_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cachetools=4.2.4=pyhd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py39he91dace_2
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - click=8.1.3=unix_pyhd8ed1ab_2
  - colorama=0.4.6=pyhd8ed1ab_0
  - cryptography=38.0.4=py39hd97740a_0
  - cudatoolkit=11.8.0=h37601d7_11
  - cudnn=8.4.1.50=hed8a83a_0
  - decorator=5.1.1=pyhd8ed1ab_0
  - docker-pycreds=0.4.0=py_0
  - executing=1.2.0=pyhd8ed1ab_0
  - frozenlist=1.3.3=py39hb9d737c_0
  - gast=0.4.0=pyh9f0ad1d_0
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.10=pyhd8ed1ab_0
  - gitpython=3.1.29=pyhd8ed1ab_0
  - google-auth=1.35.0=pyh6c4a22f_0
  - google-auth-oauthlib=0.4.6=pyhd8ed1ab_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - grpc-cpp=1.42.0=ha1441d3_1
  - grpcio=1.42.0=py39hff7568b_0
  - h5py=3.7.0=nompi_py39h817c9c5_102
  - hdf5=1.12.2=nompi_h2386368_100
  - icu=69.1=h9c3ff4c_0
  - idna=3.4=pyhd8ed1ab_0
  - importlib-metadata=5.1.0=pyha770c72_0
  - ipython=8.7.0=pyh41d4057_0
  - jedi=0.18.2=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_2
  - keras=2.7.0=pyhd8ed1ab_0
  - keras-preprocessing=1.1.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - krb5=1.19.3=h3790be6_0
  - ld_impl_linux-64=2.39=hcc3a1bd_1
  - libblas=3.9.0=16_linux64_openblas
  - libcblas=3.9.0=16_linux64_openblas
  - libcurl=7.86.0=h7bff187_1
  - libdeflate=1.13=h166bdaf_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=h516909a_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=12.2.0=h69a702a_19
  - libgfortran5=12.2.0=h337968e_19
  - libgomp=12.2.0=h65d4601_19
  - liblapack=3.9.0=16_linux64_openblas
  - libnghttp2=1.47.0=hdcd2b5c_1
  - libnsl=2.0.0=h7f98852_0
  - libopenblas=0.3.21=pthreads_h78a6416_3
  - libpng=1.6.39=h753d276_0
  - libprotobuf=3.19.4=h780b84a_0
  - libsqlite=3.40.0=h753d276_0
  - libssh2=1.10.0=haa6b8db_3
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libuuid=2.32.1=h7f98852_1000
  - libzlib=1.2.13=h166bdaf_4
  - markdown=3.4.1=pyhd8ed1ab_0
  - markupsafe=2.1.1=py39hb9d737c_2
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - multidict=6.0.2=py39hb9d737c_2
  - nccl=2.14.3.1=h0800d71_0
  - ncurses=6.3=h27087fc_1
  - numpy=1.23.5=py39h3d75532_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openssl=1.1.1s=h0b41bf4_1
  - opt_einsum=3.3.0=pyhd8ed1ab_1
  - pandas=1.5.2=py39h4661b88_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=22.3.1=pyhd8ed1ab_0
  - promise=2.3=py39hf3d152e_7
  - prompt-toolkit=3.0.36=pyha770c72_0
  - protobuf=3.19.4=py39he80948d_0
  - psutil=5.9.4=py39hb9d737c_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pybedtools=0.9.0=py39h6935b12_1
  - pycparser=2.21=pyhd8ed1ab_0
  - pygments=2.13.0=pyhd8ed1ab_0
  - pyjwt=2.6.0=pyhd8ed1ab_0
  - pyopenssl=22.1.0=pyhd8ed1ab_0
  - pysam=0.20.0=py39h9abd093_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.9.15=h47a2c10_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-flatbuffers=2.0=pyhd8ed1ab_0
  - python_abi=3.9=3_cp39
  - pytz=2022.6=pyhd8ed1ab_0
  - pyu2f=0.1.5=pyhd8ed1ab_0
  - pyyaml=6.0=py39hb9d737c_5
  - re2=2021.11.01=h9c3ff4c_0
  - readline=8.1.2=h0f457ee_0
  - requests=2.28.1=pyhd8ed1ab_1
  - requests-oauthlib=1.3.1=pyhd8ed1ab_0
  - rsa=4.9=pyhd8ed1ab_0
  - scipy=1.9.3=py39hddc5342_2
  - sentry-sdk=1.11.1=pyhd8ed1ab_0
  - setproctitle=1.3.2=py39hb9d737c_1
  - setuptools=65.5.1=pyhd8ed1ab_0
  - shortuuid=1.0.11=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=3.0.5=pyh44b312d_0
  - snappy=1.1.9=hbd366e4_2
  - sqlite=3.40.0=h4ff8645_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tensorboard=2.6.0=pyhd8ed1ab_1
  - tensorboard-data-server=0.6.1=py39hd97740a_4
  - tensorboard-plugin-wit=1.8.1=pyhd8ed1ab_0
  - tensorflow=2.7.0=cuda112py39h01bd6f0_0
  - tensorflow-base=2.7.0=cuda112py39hd98b2dd_0
  - tensorflow-estimator=2.7.0=cuda112py39h23446aa_0
  - tensorflow-gpu=2.7.0=cuda112py39h0bbbad9_0
  - termcolor=2.1.1=pyhd8ed1ab_0
  - tk=8.6.12=h27826a3_0
  - tqdm=4.64.1=pyhd8ed1ab_0
  - traitlets=5.7.0=pyhd8ed1ab_0
  - typing-extensions=4.4.0=hd8ed1ab_0
  - typing_extensions=4.4.0=pyha770c72_0
  - tzdata=2022g=h191b570_0
  - urllib3=1.26.13=pyhd8ed1ab_0
  - wandb=0.13.6=pyhd8ed1ab_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - werkzeug=2.2.2=pyhd8ed1ab_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - wrapt=1.14.1=py39hb9d737c_1
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.8.1=py39hb9d737c_0
  - zipp=3.11.0=pyhd8ed1ab_0
  - zlib=1.2.13=h166bdaf_4
  - pip:
    - contourpy==1.2.0
    - cycler==0.12.1
    - fonttools==4.47.2
    - importlib-resources==6.1.1
    - kiwisolver==1.4.5
    - matplotlib==3.8.2
    - packaging==22.0
    - pillow==10.2.0
    - pyparsing==3.1.1
    - tensorflow-addons==0.18.0
    - typeguard==2.13.3
variables:
  CLUSTER_NAME: lane
  EXTRA: '16000'
  GRES: gpu:1
  PARTITION_GPU: pfen3
  PARTITION_NO_GPU: pool1
  TIME_LIMIT: 1000:00:00
prefix: /home/azstephe/miniconda3/envs/keras2-tf27
